version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
        - "${REDIS_PORT}"
  client:
    build: client
    env_file:
      - ./.env
    links:
      - server
    ports:
      - "127.0.0.1:5000:${CLIENT_PORT}"
  server:
    build: server
    container_name: server
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis-container
    links:
      - redis
    ports:
      - "127.0.0.1:5001:${SERVER_PORT}"